### ISSUE TITLE
As a user I can create a history of the chores I do around my house 

### ISSUE THREAD

**Issue by violetapintoleite** [violetapintoleite/chore-manager-app#16] opened 2022-07-02 09:03 UTC
**Context**
Users want to be able to see the chores that they've completed to keep track of how many times they've completed. We will need to create a history/ tracker of the amount of times a chore has been completed in the individual's profile/metrics overview area.

**High-level description of the work**

**Acceptance Criteria**

**Comment by christianmartinroffey** [comment] 2022-07-05 15:26
dupe of 22

**Closed** 2022-07-05 15:26 UTC
